// Public, synthetic review walkthrough. No authentication, uploads or backend calls.
export function initReviewDemo(){
 const main=document.querySelector('main'),root=document.createElement('main');root.id='r4-review';root.hidden=true;main.after(root);
 const people=[['1','Aurora','UNIi','61200000'],['2','Cobalt','UNIi','55700000'],['3','Vega','NvSP','53200000'],['4','Orion','NvSP','50100000'],['5','Luna','NvSP','41800000'],['6','Atlas','NvSP','38900000'],['7','Sol','UNIi','35600000'],['8','Polaris','NvSP','32400000']];
 let page=1,decision='Pending review';const checks=new Set();
 root.innerHTML=`<div class="page-heading"><div><span class="eyebrow">LEADERSHIP / SAPPHIRE INTELLIGENCE</span><h1>R4 Review</h1><p>Check the evidence. Confirm the details. Reward the contribution.</p></div><span class="demo-badge">SAMPLE REVIEW</span></div>
 <div class="r4-notice">Interactive preview · Sample players and screenshots. Decisions reset on refresh; no real records or points change.</div>
 <div class="r4-layout"><aside class="r4-queue panel"><span class="eyebrow">REVIEW QUEUE</span><h2>Awaiting review <span class="pill">1</span></h2><button class="r4-queue-item"><span class="state upcoming" id="r4-status">Pending review</span><strong>Alliance Duel / VS</strong><span>Day 3 · Age of Science</span><small>Sample Lyra · 2 screenshots</small><code>VSDWED-20260923-000001</code></button><p class="hint">Points count in the week leadership accepts the submission.</p></aside>
 <section class="r4-work"><div class="r4-summary panel"><div><span class="eyebrow">SUBMISSION BRIEF</span><h2>Daily all-player leaderboard</h2><p>Wednesday · Sep 23, 2026</p><strong>#1616 [NvSP] vs #1603 [UNIi]</strong></div><div class="r4-reward"><b>+10</b><span>BOUNTY POINTS</span></div><p class="r4-wide">Expected: every leaderboard page, including the opposing alliance. Names, ranks and daily scores must be readable.</p></div>
 <div class="r4-columns"><section class="panel r4-evidence"><div class="r4-section-head"><h2>Original evidence</h2><span class="pill">SAMPLE</span></div><div class="r4-pages"><button data-r4-page="1" class="active">Page 1</button><button data-r4-page="2">Page 2</button></div><div id="r4-screenshot" class="r4-screenshot" aria-label="Illustrative leaderboard screenshot"></div><p class="hint">Illustration only. The pinned personal row is separate from the ranked page.</p></section>
 <section class="panel r4-data"><div class="r4-section-head"><h2>Extracted player data</h2><span class="state upcoming">Needs confirmation</span></div><p class="hint">Compare each value with the screenshot. Correct uncertain fields before approving.</p><div class="table-scroll"><table><thead><tr><th>RANK</th><th>PLAYER / ALLIANCE</th><th>SCORE</th></tr></thead><tbody id="r4-rows"></tbody></table></div><div class="r4-coverage"><h3>Page checks</h3><p>2 sample pages · 8 ranked players · 1 pinned personal row</p><p class="r4-warning">No automatic warning proves the leaderboard is complete. Confirm coverage against the original evidence.</p></div></section></div>
 <section class="panel r4-decision"><div><span class="eyebrow">FINAL REVIEW</span><h2>Ready for a decision?</h2></div><div class="r4-checks">${['Player identities checked','Wednesday and bounty date checked','Both alliances and all pages checked','Overlaps and pinned row checked'].map((text,i)=>`<label><input type="checkbox" data-r4-check="${i}">${text}</label>`).join('')}</div><label class="r4-reason">Review note<textarea id="r4-note" rows="2" minlength="8" maxlength="1000"></textarea></label><div class="r4-actions"><button id="r4-request">Request clearer evidence</button><button id="r4-approve" class="primary" disabled>Approve sample submission</button><button id="r4-reset">Reset sample</button></div><p id="r4-result" role="status">Complete all four checks and add a review note to approve.</p></section></section></div>`;
 const paint=()=>{const shown=people.slice((page-1)*4,page*4);root.querySelector('#r4-screenshot').innerHTML=`<div class="r4-game-title">RANKING</div><div class="r4-game-tabs"><b>Daily Rank</b><span>Weekly Rank</span></div><div class="r4-game-days">MON · TUE · <b>WED</b> · THU · FRI · SAT</div><div class="r4-game-labels">RANKING / COMMANDER / POINTS</div>${shown.map(([rank,name,alliance,score])=>`<div class="r4-game-row rank-bg-${rank}"><b>${rank}</b><span><strong>${name}</strong><small>[${alliance}] ${alliance==='NvSP'?'Nova Sapphire':'Sample opponent'}</small></span><strong>${Number(score).toLocaleString('en-US')}</strong></div>`).join('')}<div class="r4-game-row r4-pinned"><b>155</b><span><strong>Lyra</strong><small>[NvSP] Nova Sapphire</small></span><strong>8,200,000</strong></div><div class="r4-game-footer">☐ Your Alliance</div>`;
 root.querySelector('#r4-rows').innerHTML=shown.map(([rank,name,alliance,score])=>`<tr><td>${rank}</td><td><strong class="player-name">${name}</strong><small class="r4-alliance">[${alliance}]</small></td><td><input aria-label="${name} score" inputmode="numeric" maxlength="16" data-r4-score="${Number(rank)-1}" value="${score}"></td></tr>`).join('');root.querySelectorAll('[data-r4-page]').forEach(b=>{b.classList.toggle('active',Number(b.dataset.r4Page)===page);b.setAttribute('aria-pressed',String(Number(b.dataset.r4Page)===page));});};
 const refresh=()=>{root.querySelector('#r4-approve').disabled=decision!=='Pending review'||checks.size!==4||root.querySelector('#r4-note').value.trim().length<8||people.some(r=>!/^\d+$/.test(r[3])||!Number.isSafeInteger(Number(r[3])));root.querySelector('#r4-request').disabled=decision!=='Pending review';};
 // The image is an immutable illustration; edits change only draft values.
 const originals=people.map(r=>r[3]);
 const originalPaint=paint;const paintEvidence=()=>{const draft=people.map(r=>r[3]);people.forEach((r,i)=>r[3]=originals[i]);originalPaint();people.forEach((r,i)=>r[3]=draft[i]);root.querySelectorAll('[data-r4-score]').forEach(n=>{n.value=people[Number(n.dataset.r4Score)][3];n.disabled=decision!=='Pending review';});};
 root.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.dataset.r4Page){page=Number(b.dataset.r4Page);paintEvidence();}if(b.id==='r4-approve'&&!b.disabled){decision='Accepted';root.querySelector('#r4-status').textContent=decision;root.querySelector('#r4-result').textContent='Sample approved. No real points awarded.';root.querySelectorAll('input,textarea').forEach(n=>n.disabled=true);refresh();}if(b.id==='r4-request'){if(root.querySelector('#r4-note').value.trim().length<8){root.querySelector('#r4-result').textContent='Add a review note explaining what needs to be clearer.';return;}decision='Changes requested';root.querySelector('#r4-status').textContent=decision;root.querySelector('#r4-result').textContent='Sample returned for clearer evidence. No message was sent.';root.querySelectorAll('input,textarea').forEach(n=>n.disabled=true);refresh();}if(b.id==='r4-reset'){decision='Pending review';checks.clear();people.forEach((r,i)=>r[3]=originals[i]);root.querySelectorAll('input,textarea').forEach(n=>{n.disabled=false;if(n.type==='checkbox')n.checked=false;});root.querySelector('#r4-note').value='';root.querySelector('#r4-status').textContent=decision;root.querySelector('#r4-result').textContent='Complete all four checks and add a review note to approve.';paintEvidence();refresh();}});
 root.addEventListener('input',event=>{const n=event.target;if(n.dataset.r4Check!==undefined)n.checked?checks.add(n.dataset.r4Check):checks.delete(n.dataset.r4Check);if(n.dataset.r4Score!==undefined)people[Number(n.dataset.r4Score)][3]=n.value;refresh();});
 const nav=document.createElement('button');nav.id='r4-nav';nav.textContent='R4 Review';document.querySelector('.rail nav').append(nav);
 const show=()=>{main.hidden=true;root.hidden=false;document.querySelectorAll('[data-view]').forEach(b=>b.classList.remove('active'));nav.classList.add('active');document.querySelector('#breadcrumb-current').textContent='R4 REVIEW';window.scrollTo(0,0);};nav.onclick=()=>{history.replaceState(null,'','#r4-review');show();};
 document.addEventListener('click',ev=>{if(ev.target.closest('[data-view]')){main.hidden=false;root.hidden=true;nav.classList.remove('active');history.replaceState(null,'',location.pathname);}});paintEvidence();if(location.hash==='#r4-review')show();
}
