// Public, synthetic review walkthrough. No authentication, uploads or backend calls.
export function initReviewDemo(){
 const main=document.querySelector('main'),root=document.createElement('main');root.id='r4-review';root.hidden=true;main.after(root);
 const people=[['1','Subrata Dinda F2P','UNIi','61646550'],['2','OLdGuard','UNIi','55927650'],['3','SnoopyEgg','NvSP','53967600'],['4','KillerReddy','NvSP','50292200'],['5','StankyFanger','NvSP','41874500'],['6','A Alone','NvSP','38956800'],['7','Thúy Loan','NvSP','35769900']];
 let page=1,decision='Pending review';const checks=new Set(),reviewedPages=new Set(),profileStats=new Map();const evidencePages=[1];
 root.innerHTML=`<div class="page-heading"><div><span class="eyebrow">LEADERSHIP / SAPPHIRE INTELLIGENCE</span><h1>R4 Review</h1><p>Check the evidence. Confirm the details. Reward the contribution.</p></div><span class="demo-badge">SAMPLE REVIEW</span></div>
 <div class="r4-notice">Real screenshot · Rows manually transcribed for this preview. Review actions are simulations and reset on refresh.</div>
 <div class="r4-layout"><aside class="r4-queue panel"><span class="eyebrow">REVIEW QUEUE</span><h2>Awaiting review <span class="pill">1</span></h2><button class="r4-queue-item"><span class="state upcoming" id="r4-status">Pending review</span><strong>Alliance Duel / VS</strong><span>Day 3 · Age of Science</span><small>1 screenshot · Demonstration submission</small><code>VSDWED-20260923-000001</code></button><p class="hint">Points count in the week leadership accepts the submission.</p></aside>
 <section class="r4-work"><div class="r4-summary panel"><div><span class="eyebrow">SUBMISSION BRIEF</span><h2>Daily all-player leaderboard</h2><p>Wednesday · Sep 23, 2026</p><strong>#1616 [NvSP] vs #1603 [UNIi]</strong></div><div class="r4-reward"><b>+10</b><span>BOUNTY POINTS</span></div><p class="r4-wide">Expected: every leaderboard page, including the opposing alliance. Names, ranks and daily scores must be readable.</p></div>
 <div class="r4-columns"><section class="panel r4-evidence"><div class="r4-section-head"><h2>Original evidence</h2><span class="pill">SCREENSHOT</span></div><div class="r4-pages"><button data-r4-page="1" class="active">Page 1</button></div><button id="r4-page-reviewed">Mark this screenshot reviewed</button><p id="r4-page-progress" role="status">0 / 1 screenshots reviewed</p><div id="r4-screenshot" class="r4-screenshot" aria-label="Illustrative leaderboard screenshot"></div><p class="hint">Original uploaded screenshot. The pinned rank-155 row is separate from ranks 1–7.</p></section>
 <section class="panel r4-data"><div class="r4-section-head"><h2>Extracted player data</h2><span class="state upcoming">Needs confirmation</span></div><p class="hint">These rows were manually transcribed, not produced by OCR. Compare each value with the screenshot.</p><div class="table-scroll"><table><thead><tr><th>RANK</th><th>PLAYER / ALLIANCE</th><th>SCORE</th></tr></thead><tbody id="r4-rows"></tbody></table></div><div class="r4-coverage"><h3>Page checks</h3><p>1 screenshot · 7 ranked players · 1 pinned personal row</p><p class="r4-warning">More leaderboard pages are needed to confirm full coverage. This screenshot alone is not a complete submission.</p></div></section></div>
 <section class="panel r4-decision"><div><span class="eyebrow">FINAL REVIEW</span><h2>Ready for a decision?</h2></div><div class="r4-checks">${['Player identities checked','Wednesday and bounty date checked','Both alliances and all pages checked','Overlaps and pinned row checked'].map((text,i)=>`<label><input type="checkbox" data-r4-check="${i}">${text}</label>`).join('')}</div><label class="r4-reason">Review note<textarea id="r4-note" rows="2" minlength="8" maxlength="1000"></textarea></label><div class="r4-actions"><button id="r4-request">Request clearer evidence</button><button id="r4-approve" class="primary" disabled>Approve sample submission</button><button id="r4-reset">Reset sample</button></div><p id="r4-result" role="status">Review every submitted screenshot, confirm the checks and add a note to approve.</p></section><section class="panel r4-decision" id="r4-profiles"><span class="eyebrow">PLAYER PROFILES</span><h2>Saved player stats</h2><p class="hint">Demo profile history only. Live accounts are not changed.</p><label>Player <select id="r4-profile-select"></select></label><div id="r4-profile-result" role="status">No approved stats saved yet.</div></section></section></div>`;
 const paint=()=>{const shown=people;root.querySelector('#r4-screenshot').innerHTML='<a href="vs-review-example.png" target="_blank" rel="noopener"><img src="vs-review-example.png" alt="Alliance Duel daily ranking, Wednesday selected, ranks 1–7 and pinned rank 155" style="display:block;width:100%;height:auto;max-height:850px;object-fit:contain"></a>';
 root.querySelector('#r4-rows').innerHTML=shown.map(([rank,name,alliance,score])=>`<tr><td>${rank}</td><td><strong class="player-name">${name}</strong><small class="r4-alliance">[${alliance}]</small></td><td><input aria-label="${name} score" inputmode="numeric" maxlength="16" data-r4-score="${Number(rank)-1}" value="${score}"></td></tr>`).join('');root.querySelectorAll('[data-r4-page]').forEach(b=>{b.classList.toggle('active',Number(b.dataset.r4Page)===page);b.setAttribute('aria-pressed',String(Number(b.dataset.r4Page)===page));});};
 const refresh=()=>{root.querySelector('#r4-approve').disabled=decision!=='Pending review'||reviewedPages.size!==evidencePages.length||checks.size!==4||root.querySelector('#r4-note').value.trim().length<8||people.some(r=>!/^\d+$/.test(r[3])||!Number.isSafeInteger(Number(r[3])));root.querySelector('#r4-page-reviewed').disabled=decision!=='Pending review'||reviewedPages.has(page);root.querySelector('#r4-page-progress').textContent=reviewedPages.size+' / '+evidencePages.length+' screenshots reviewed';root.querySelector('#r4-request').disabled=decision!=='Pending review';};
 // The image is an immutable illustration; edits change only draft values.
 const originals=people.map(r=>r[3]);
 const originalPaint=paint;const paintEvidence=()=>{const draft=people.map(r=>r[3]);people.forEach((r,i)=>r[3]=originals[i]);originalPaint();people.forEach((r,i)=>r[3]=draft[i]);root.querySelectorAll('[data-r4-score]').forEach(n=>{n.value=people[Number(n.dataset.r4Score)][3];n.disabled=decision!=='Pending review';});};
 const showProfile=()=>{const index=Number(root.querySelector('#r4-profile-select').value),stat=profileStats.get(index),out=root.querySelector('#r4-profile-result');out.replaceChildren();if(!stat){out.textContent='No approved stats saved yet.';return;}for(const text of [stat.name,'Alliance Duel / VS · Wednesday · Sep 23, 2026','Rank '+stat.rank+' · '+Number(stat.score).toLocaleString('en-US')+' points','Source: screenshot 1 · Approved in this demo']){const p=document.createElement('p');p.textContent=text;out.append(p);}};
 people.forEach((row,i)=>{const option=document.createElement('option');option.value=String(i);option.textContent=row[1]+' ['+row[2]+']';root.querySelector('#r4-profile-select').append(option);});root.querySelector('#r4-profile-select').addEventListener('change',showProfile);
 root.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.dataset.r4Page){page=Number(b.dataset.r4Page);paintEvidence();refresh();}if(b.id==='r4-page-reviewed'&&decision==='Pending review'){reviewedPages.add(page);refresh();}if(b.id==='r4-approve'&&!b.disabled){people.forEach(([rank,name,alliance,score],i)=>profileStats.set(i,{rank,name,alliance,score,evidencePage:1,bountyRef:'VSDWED-20260923-000001',gameDate:'2026-09-23'}));showProfile();decision='Accepted';root.querySelector('#r4-status').textContent=decision;root.querySelector('#r4-result').textContent='All submitted screenshots approved. Stats saved to demo player profiles. No live data or points changed.';root.querySelectorAll('input,textarea').forEach(n=>n.disabled=true);refresh();}if(b.id==='r4-request'){if(root.querySelector('#r4-note').value.trim().length<8){root.querySelector('#r4-result').textContent='Add a review note explaining what needs to be clearer.';return;}decision='Changes requested';root.querySelector('#r4-status').textContent=decision;root.querySelector('#r4-result').textContent='Sample returned for clearer evidence. No message was sent.';root.querySelectorAll('input,textarea').forEach(n=>n.disabled=true);refresh();}if(b.id==='r4-reset'){decision='Pending review';checks.clear();reviewedPages.clear();profileStats.clear();showProfile();people.forEach((r,i)=>r[3]=originals[i]);root.querySelectorAll('input,textarea').forEach(n=>{n.disabled=false;if(n.type==='checkbox')n.checked=false;});root.querySelector('#r4-note').value='';root.querySelector('#r4-status').textContent=decision;root.querySelector('#r4-result').textContent='Review every submitted screenshot, confirm the checks and add a note to approve.';paintEvidence();refresh();}});
 root.addEventListener('input',event=>{const n=event.target;if(n.dataset.r4Check!==undefined)n.checked?checks.add(n.dataset.r4Check):checks.delete(n.dataset.r4Check);if(n.dataset.r4Score!==undefined){people[Number(n.dataset.r4Score)][3]=n.value;reviewedPages.delete(page);checks.delete('0');root.querySelector('[data-r4-check="0"]').checked=false;}refresh();});
 const nav=document.createElement('button');nav.id='r4-nav';nav.textContent='R4 Review';document.querySelector('.rail nav').append(nav);
 const show=()=>{main.hidden=true;root.hidden=false;document.querySelectorAll('[data-view]').forEach(b=>b.classList.remove('active'));nav.classList.add('active');document.querySelector('#breadcrumb-current').textContent='R4 REVIEW';window.scrollTo(0,0);};nav.onclick=()=>{history.replaceState(null,'','#r4-review');show();};
 document.addEventListener('click',ev=>{if(ev.target.closest('[data-view]')){main.hidden=false;root.hidden=true;nav.classList.remove('active');history.replaceState(null,'',location.pathname);}});paintEvidence();refresh();if(location.hash==='#r4-review')show();
}
