import {test} from 'node:test';import assert from 'node:assert/strict';
import {createHistoryStore,historyTable,pageIsReviewed,submissionCode} from './submission-history.js';
import {createRowApprovals} from './review-row-state.js';
test('rejection needs reason, records rejected time, no points, cannot overwrite decision',()=>{const s=createHistoryStore();assert.equal(s.decide('VSDWED-20260923-000001','Rejected','  '),false);assert.equal(s.decide('VSDWED-20260923-000001','Rejected','Missing pages','2026-09-24T15:00:00Z'),true);const r=s.list()[0];assert.equal(r.reason,'Missing pages');assert.equal(r.points,0);assert.equal(r.approvedAt,null);assert.equal(r.rejectedAt,'2026-09-24T15:00:00Z');assert.equal(s.decide(r.id,'Approved'),false);s.reset();assert.equal(s.list()[0].status,'Pending review');});
test('approval records points and approval date only; escapes rejection text',()=>{const s=createHistoryStore();s.decide('VSDWED-20260923-000001','Approved');assert.equal(s.list()[0].points,10);assert.equal(s.list()[0].rejectedAt,null);s.reset();s.decide('VSDWED-20260923-000001','Rejected','<img onerror=alert(1)>');assert.ok(historyTable(s.list()).includes('&lt;img'));});
test('pages follow only their rows and edits invalidate that page',()=>{const a=createRowApprovals([{profileRef:'a',score:'123'},{profileRef:'b',score:'456'}]);a.confirmPlayer(0,true);a.confirmScore(0,true);assert.equal(pageIsReviewed([0],a),true);assert.equal(pageIsReviewed([1],a),false);assert.equal(pageIsReviewed([],a),false);a.setScore(0,'124');assert.equal(pageIsReviewed([0],a),false);});

test('bounty stays shared and player suffix stays stable across bounties',()=>{assert.equal(submissionCode('VSDWED-20260923','000001'),'VSDWED-20260923-000001');assert.equal(submissionCode('VSDWED-20260923','000002'),'VSDWED-20260923-000002');assert.equal(submissionCode('DNDTHU-20260924','000002'),'DNDTHU-20260924-000002');const s=createHistoryStore();s.add({id:submissionCode('VSDWED-20260923','000002'),memberId:'000002'});s.decide('VSDWED-20260923-000001','Rejected','Missing pages');assert.equal(s.list()[1].status,'Pending review');});

test('accept without bounty finalizes approval at zero points and cannot later reward it',()=>{const s=createHistoryStore();const id='VSDWED-20260923-000001';assert.equal(s.decide(id,'Approved','', '2026-09-25T01:00:00Z',{awardPoints:false}),true);const row=s.list()[0];assert.equal(row.status,'Approved');assert.equal(row.points,0);assert.equal(row.rewardDisposition,'waived');assert.equal(row.approvedAt,'2026-09-25T01:00:00Z');assert.equal(row.rejectedAt,null);assert.equal(s.decide(id,'Approved'),false);assert.match(historyTable(s.list()),/Accepted · No bounty points/);s.reset();assert.equal(s.list()[0].status,'Pending review');});
