// In-memory demo records only. No Portal or member-account writes.
export const demoMemberId='000001';
export function submissionCode(bountyCode,playerId){if(!/^[A-Z]+-\d{8}$/.test(bountyCode)||!/^\d{6}$/.test(playerId))throw Error('Invalid bounty or player identifier');return bountyCode+'-'+playerId;}
const initial={id:'VSDWED-20260923-000001',memberId:demoMemberId,bountyCode:'VSDWED-20260923',title:'Daily VS Leaderboard (Wednesday, Age of Science)',code:'VSDWED-20260923-000001',submittedAt:'2026-09-24T04:00:00Z',status:'Pending review',approvedAt:null,rejectedAt:null,points:0,reason:''};
export function createHistoryStore(seed=[initial]){
 const rows=new Map(seed.map(r=>[r.id,structuredClone(r)]));
 return {list:()=>structuredClone([...rows.values()]),add(row){if(!rows.has(row.id))rows.set(row.id,{...row,status:'Pending review',approvedAt:null,rejectedAt:null,points:0,reason:''});},decide(id,status,reason='',now=new Date().toISOString(),options={}) {const row=rows.get(id);if(!row||row.status!=='Pending review'||!['Approved','Rejected'].includes(status))return false;if(status==='Rejected'&&!reason.trim())return false;Object.assign(row,{status,reason:status==='Rejected'?reason.trim():'',approvedAt:status==='Approved'?now:null,rejectedAt:status==='Rejected'?now:null,points:status==='Approved'&&options.awardPoints!==false?10:0,rewardDisposition:status==='Approved'?(options.awardPoints===false?'waived':'awarded'):'none'});return true;},reset(){rows.clear();seed.forEach(r=>rows.set(r.id,structuredClone(r)));}};
}
export const submissionHistory=createHistoryStore();
export function historyChanged(){document.dispatchEvent(new Event('demo-history-change'));}
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=value=>value?new Date(value).toLocaleString(undefined,{month:'short',day:'numeric',year:'numeric',hour:'2-digit',minute:'2-digit'}):'—';
export function historyTable(rows=submissionHistory.list().filter(r=>r.memberId===demoMemberId)) {return `<div class="table-scroll"><table class="submission-history"><thead><tr><th>BOUNTY</th><th>SUBMITTED</th><th>APPROVED</th><th>REJECTED</th><th>POINTS</th><th>STATUS</th><th>REASON</th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${escape(r.title)}</strong><small>${escape(r.code)}</small></td><td>${escape(date(r.submittedAt))}</td><td>${escape(date(r.approvedAt))}</td><td>${escape(date(r.rejectedAt))}</td><td>${r.points}${r.rewardDisposition==='waived'?'<small>Accepted · No bounty points</small>':''}</td><td><span tabindex="0" role="img" class="review-indicator ${r.status==='Approved'?'approved':r.status==='Rejected'?'rejected':'pending'}" title="${r.status}" aria-label="${r.status}">${r.status==='Approved'?'✓':r.status==='Rejected'?'✕':'●'}<span class="review-tooltip">${r.status}</span></span></td><td>${escape(r.reason||'—')}</td></tr>`).join('')}</tbody></table></div>`;}
export function pageIsReviewed(rowIndexes,approvals){return rowIndexes.length>0&&rowIndexes.every(i=>approvals.view(i).ready);}
